export { canvas, Canvas } from './Canvas'
export { Frame } from './Frame'
export { FrameHeaderButtonComponent } from './FrameHeaderButtonComponent'
export { getNextZIndex } from './zindex'
export type { AddFrameConfig, ButtonConfig, FrameEntry } from './types'
