//----------------------------------------------------------------------------------------------------
// ViewerComponent
//----------------------------------------------------------------------------------------------------
export const ViewerComponent = `

The ViewerComponent is a React component.

The ViewerComponent is implemented in the file lucy/frontend/src/ViewerComponent.

The ViewerComponent takes two props:

- encodedImage is a base64-encoded string containing either a png or a jpeg.

- mimeType is either 'png' or 'jpg'.

The ViewerComponent displays the image most recently generated by the backend server,
or a black box if there is no such image.

The image is centered in the surrounding frame's viewport.  The image is sized to be as
large as possible while maintaining it's aspect ration and without causing clipping in 
either the horizontal or vertical direction.

`
