//----------------------------------------------------------------------------------------------------
// viewerComponent
//----------------------------------------------------------------------------------------------------
export const viewerComponent = `

The ViewerComponent is a React component .

The ViewerComponent takes two props:

- encodedImage is a base64-encoded string containing either a png or a jpeg.

- mimeType is either 'png' or 'jpg'.

The ViewerComponent displays the image most recently generated by the backend server,
or a black box if there is no such image.

The image is centered in the space allocated for the ViewComponent.  

The image is sized to be as large as possible while maintaining it's aspect ration 
and without causing clipping in either the horizontal or vertical direction.

The image has a context menu with these options:

- "Download image": download the image as is typical in web apps.

- "Save as pic": does alert('save')

- "Zoom": adds a ZoomApplet to the canvas.  The encoded image and mime type are passed as props.  

While the surrounding workbook has an API call to the generate-pic is pending show a spinner.

`
